name: schism
channels:
  - defaults
  - cadwr-dms
  - conda-forge
dependencies:
  - python>=3.9
  - dms-datastore
  - schimpy
  - shapely
  - rtree
  - numba
  - pyproj
  - vtools3
  - scipy
  - gdal
  - libgdal
  - cfunits
  - curl
  - cycler
  - dask
  - xarray
  - netcdf4
  - pandas
  - sympy
  - statsmodels
  - pywavelets
  - openpyxl
  - rasterstats
  - beautifulsoup4
  - intake
  - seaborn
  - sphinx-argparse
  - pytest-runner
  - sphinx
  - palettable
  - nbsphinx
  - numpydoc
  - nodepy
  - ipykernel
  - spyder-kernels>=1.9
  - scikit-learn
  - docutils
  - pyhecdss
  - openpyxl
  - cookiecutter
  - bokeh
  - bleach
  - sphinx_rtd_theme
  - hvplot
  - sphinxcontrib-bibtex
