from builtins import open, file, str
from pandas.compat import u
import pandas as pd

station_variables = ["elev", "air pressure", "wind_x", "wind_y",
                     "temp", "salt", "u", "v", "w"]

def read_station_in(fpath):
    """Read a SCHISM station.in file into a pandas DataFrame
    
    .. note:: 
        This only reads the tabular part, and assumes the BayDelta SCHISM format with columns:
        index x y z ! id subloc "Name"
        
        Note that there is no header and the delimiter is a space. Also note that the text beginning with ! 
        is extra BayDeltaSCHISM extra metadata, not required for vanilla SCHISM

     Parameters
     ----------
     fpath : fname
        Path to input station.in style file
        
     Returns
     -------    
     Result : DataFrame
         DataFrame with hierarchical index (id,subloc) and columns x,y,z,name
                
    """

    with open(fpath,'r') as f:
        request = f.readline()
        n_entry = f.readline()
        stations = pd.read_csv(f,sep = "\s+",header=None,
                       names=["index","x","y","z","excl","id","subloc","name"],
                       usecols=["x","y","z","id","subloc","name"],
                       index_col=["id","subloc"],na_values="-",keep_default_na=True)
    return stations



def write_station_in(fpath,station_in,request=None):
    """Write a SCHISM station.in file given a pandas DataFrame of metadata
    
     Parameters
     ----------
     fpath : fname
        Path to output station.in file

     station_in : DataFrame
        DataFrame that has station id, x, y, z, name and subloc labels (id is the station id, index will be autogenerated)

     request :  'all' or list(str)
        List of variables to put in output request from the choices 'elev', 'air pressure', 'wind_x', 'wind_y', 'temp', 'salt', 'u', 'v', 'w'
        or 'all' to include them all
    """
    request_int = [0]*len(station_variables)
    request_str = station_variables if request == "all" else request
    request_int = [(1 if var in request_str else 0) for var in station_variables]    
    dfmerged =station_in.reset_index() 
    dfmerged.index += 1
    dfmerged["excl"] = "!"
    buffer = "1 0 1 0\n{}\n".format(dfmerged.index[-1])
    buffer2 = dfmerged.to_csv(None,columns=["x","y","z","excl","id","subloc","name"],index_label="id",
        sep=' ',float_format="%.2f",header=False)
    with open(fpath,"w",newline='') as f: 
        f.write(u"1 1 1 1\n")
        f.write(u"21\n")
        f.write(u(buffer2))


def read_station_depth(fpath):
    """Read a BayDeltaSCHISM station_depths.csv  file into a pandas DataFrame
    
       The BayDelta SCHISM format has a header and uses "," as the delimiter and has these columns:
       id,subloc,z
       
       The id is the station id, which is the key that joins this file to the station database. 'subloc' is a label that describes
       the sublocation or depth and z is the actual elevation of the instrument
       
       Example might be:
       id,subloc,z
       12345,top,-0.5
       
       Other columns are allowed, but this will commonly merged with the station database file so we avoid column names like 'name' that might collide
        
     Parameters
     ----------
     fpath : fname
        Path to input station.in style file
        
     Returns
     -------    
     Result : DataFrame
         DataFrame with hierarchical index (id,subloc) and data column z
                
    """
    return pd.read_csv(fpath,sep=",",header=0,index_col=["id","subloc"])




def read_station_dbase(fpath):
    """Read a BayDeltaSCHISM station data base csv  file into a pandas DataFrame
    
       The BayDelta SCHISM format is open, but expects these columns:
       index x y z ! id subloc "Name"
             
        
     Parameters
     ----------
     fpath : fname
        Path to input station.in style file
        
     Returns
     -------    
     Result : DataFrame
         DataFrame with hierarchical index (id,subloc) and columns x,y,z,name
                
    """
    return  pd.read_csv(fpath,sep=",",header=0,index_col="id")

def merge_station_depth(station_dbase,station_depth,default_z):
    """Merge BayDeltaSCHISM station database with depth file, producing the union of all stations and depths including a default entry for stations with no depth entry            
        
     Parameters
     ----------
     station_dbase : DataFrame 
        This should be the input that has only the station id as an index and includes other metadata like x,y, 

     station_depth : DataFrame 
        This should have (id,subloc) as an index
        
     Returns
     -------    
     Result : DataFrame
         DataFrame that links the information.
                
    """
    merged =  station_dbase.merge(station_depth.reset_index("subloc"),
                left_on="id",right_on="id",
                how='left').set_index("subloc",append=True)
    merged.loc[merged.z.isna(),"z"] = default_z
    return merged

def read_obs_links(fpath):
    """Read an obs_links csv file which has comma as delimiter and (id,subloc) as index """
    return pd.read_csv(fpath,sep=",",header=0,index_col=["id","subloc"])


def read_station_out(fpath_base,stationinfo,var=None,start=None):
    if var is None:
        fname = fpath_base
    else:
        try:
            fileno = station_variables.index(var)
        except ValueError:
            raise ValueError("Variable name {} not on list: {}.format(var,station_variables")
        fname = "{}_{:d}".format(fileno)
    data = pandas.read_csv(fpath,var,sep="\s+",index_col=0,
                           header=None,names = stationinfo.index,dtype='d')
    if start is not None:
        data = elapsed_to_date(data)
    return data

def example():
    print(read_station_in("example_station.in"))  
    stations_utm = read_station_dbase("stations_utm.csv")
    sdepth = read_station_depth("station_depth.csv")
    stations_in = merge_station_depth(stations_utm,sdepth,default_z=-0.5)
    #stations_in = pd.merge(stations_utm,sdepth,how='inner',left_index=True,right_index=True)
    print(stations_in)
    station_request = ["salt","elev"]
    write_station_in("station.in",stations_in,request=station_request)
    #stations_in = read_station_in("station.in")
    obs_links = read_obs_links("obs_links.csv")
    merged = stations_in.merge(obs_links,left_index=True,right_index=True,how="left")
   
    if True:
        print("**")
        print(obs_links)
        print("**")
        print(stations_in)
        print("**")
        print(stations_utm)
        print("**")
        print(merged)

if __name__ == '__main__':
    example()



